package org.example;

import javafx.scene.shape.Rectangle;

import java.util.HashMap;
import java.util.Map;

public class AI {
    private final boardeval evaluator;

    public AI(boardeval eval) {
        this.evaluator = eval;
    }

    public record Move(int rotation, int column, int row, int score) {}

    // each piece's spawn layout (col,row), taken from controller.makeShape()
    private static final Map<String, int[][]> BASE_SHAPES = new HashMap<>();
    static {
        BASE_SHAPES.put("l", new int[][]{{0, 0}, {0, 1}, {1, 1}, {2, 1}});
        BASE_SHAPES.put("ll", new int[][]{{2, 0}, {0, 1}, {1, 1}, {2, 1}});
        BASE_SHAPES.put("square", new int[][]{{0, 0}, {1, 0}, {0, 1}, {1, 1}});
        BASE_SHAPES.put("s", new int[][]{{2, 0}, {1, 0}, {1, 1}, {0, 1}});
        BASE_SHAPES.put("zig", new int[][]{{1, 0}, {0, 0}, {1, 1}, {2, 1}});
        BASE_SHAPES.put("t", new int[][]{{0, 0}, {1, 0}, {1, 1}, {2, 0}});
        BASE_SHAPES.put("line", new int[][]{{0, 0}, {1, 0}, {2, 0}, {3, 0}});
    }

    // the 4 rotation states per piece, generated by rotating the spawn shape 90 degrees at a time
    private static final Map<String, int[][][]> SHAPES = new HashMap<>();
    static {
        for (Map.Entry<String, int[][]> entry : BASE_SHAPES.entrySet()) {
            int[][][] states = new int[4][][];
            int[][] current = normalize(entry.getValue());
            for (int i = 0; i < states.length; i++) {
                states[i] = current;
                current = rotateCW(current);
            }
            SHAPES.put(entry.getKey(), states);
        }
    }

    private static int[][] rotateCW(int[][] cells) {
        int[][] rotated = new int[cells.length][2];
        for (int i = 0; i < cells.length; i++) {
            rotated[i][0] = -cells[i][1];
            rotated[i][1] = cells[i][0];
        }
        return normalize(rotated);
    }

    private static int[][] normalize(int[][] cells) {
        int minCol = Integer.MAX_VALUE, minRow = Integer.MAX_VALUE;
        for (int[] cell : cells) {
            minCol = Math.min(minCol, cell[0]);
            minRow = Math.min(minRow, cell[1]);
        }
        int[][] result = new int[cells.length][2];
        for (int i = 0; i < cells.length; i++) {
            result[i][0] = cells[i][0] - minCol;
            result[i][1] = cells[i][1] - minRow;
        }
        return result;
    }

    private static int maxCol(int[][] cells) {
        int max = 0;
        for (int[] cell : cells) max = Math.max(max, cell[0]);
        return max;
    }

    private static int maxRow(int[][] cells) {
        int max = 0;
        for (int[] cell : cells) max = Math.max(max, cell[1]);
        return max;
    }

    private static int[][] cloneBoard(int[][] board) {
        int[][] copy = new int[board.length][];
        for (int i = 0; i < board.length; i++) copy[i] = board[i].clone();
        return copy;
    }

    // rows the shape falls before landing on the stack/floor; -1 if it can't fit at all
    private int simulateDrop(int[][] board, int[][] cells, int colOffset) {
        int height = board[0].length;
        int width = maxCol(cells) + 1;
        int landing = Integer.MAX_VALUE;
        for (int relCol = 0; relCol < width; relCol++) {
            int shapeBottom = -1;
            for (int[] cell : cells) {
                if (cell[0] == relCol) shapeBottom = Math.max(shapeBottom, cell[1]);
            }
            if (shapeBottom < 0) continue;
            int col = colOffset + relCol;
            int firstFilled = height;
            for (int row = 0; row < height; row++) {
                if (board[col][row] != 0) {
                    firstFilled = row;
                    break;
                }
            }
            landing = Math.min(landing, (firstFilled - 1) - shapeBottom);
        }
        return landing < 0 ? -1 : landing;
    }

    // tries every rotation and column for the current piece and scores each resulting board with boardeval
    public Move bestMove(form piece, int[][] board) {
        int[][][] states = SHAPES.get(piece.getName());
        if (states == null) return null;

        int width = board.length;
        Move best = null;
        for (int rotation = 0; rotation < states.length; rotation++) {
            int[][] cells = states[rotation];
            int shapeWidth = maxCol(cells) + 1;
            for (int col = 0; col <= width - shapeWidth; col++) {
                int rowOffset = simulateDrop(board, cells, col);
                if (rowOffset < 0) continue;

                int[][] candidate = cloneBoard(board);
                for (int[] cell : cells) {
                    candidate[col + cell[0]][rowOffset + cell[1]] = 1;
                }

                int score = evaluator.evaluate(candidate);
                if (best == null || score > best.score()) {
                    best = new Move(rotation, col, rowOffset, score);
                }
            }
        }
        return best;
    }

    // hard-drops the piece straight to its landing row at the chosen rotation/column
    public void applyMove(form piece, Move move) {
        int[][] cells = SHAPES.get(piece.getName())[move.rotation()];
        Rectangle[] rects = {piece.a, piece.b, piece.c, piece.d};

        for (int i = 0; i < rects.length; i++) {
            rects[i].setX((move.column() + cells[i][0]) * Tetris.size);
            rects[i].setY((move.row() + cells[i][1]) * Tetris.size);
        }
        piece.form = move.rotation() + 1;
    }

    // evaluates then immediately applies the best move; returns null if the piece has nowhere to land
    public Move play(form piece, int[][] board) {
        Move move = bestMove(piece, board);
        if (move != null) applyMove(piece, move);
        return move;
    }
}
